### ISSUE TITLE
New pypi version?

### ISSUE THREAD

**Issue by dellis23** [tomerfiliba/reedsolomon#10]
I'd like to use some of the newer features, namely the `error_pos` argument to `RSCodec.decode`.  It seems like the latest version in pypi is 0.3.  Is it possible to get the latest version pushed?

**Comment by kc2rxo** [comment]
Old issue, but ran into this today after 4 hours of fighting with my system and trying other implementations only to discover this was causing me pain. Took digging into the source that pypi installed for me to notice the difference.

If anything just mention it at the top of the README that v0.3 is what pypi is sourcing, not the master.

**Comment by lrq3000** [comment]
@tomerfiliba if you give me access to the reedsolo repo on pypi (same account name there, LRQ3000 in lowercase), then I can take care of updating it.

**Comment by lrq3000** [comment]
@tomerfiliba Also if you give me access to this repo I can merge in the 2 remaining PRs which corrects a few issues and compatibility with Python 3.7

**Comment by tomerfiliba** [comment]
@lrq3000 done

**Comment by lrq3000** [comment]
@tomerfiliba Ok awesome! Thank you very much, I'll take care of these updates right away!

**Comment by lrq3000** [comment]
Done, and I cleaned up a bit the code to upgrade to Python 3.7 and make Travis CI happy again, I think we can close this issue :-) Please reopen if `pip install --upgrade reedsolo` does not fix your issue!
