### ISSUE TITLE
Not compatible with matlab's rsenc/rsdec; only deal with n=255.

### ISSUE THREAD

**Issue by felix021** [tomerfiliba/reedsolomon#2]
Hey buddy, as is said in the mail, I tried to improve this package, but encountered an error in the decoder. The improvements to the encoder may help, so I send it to you, hoping that you (or some one else) can (easily) fix it. 

p.s. Source code is not permitted to be attached here.

**Comment by lrq3000** [comment]
If you still experience an issue, please try the new release, it has been thoroughly unit tested, or else if it's ok now, please close this thread :)
