### ISSUE TITLE
Enable multiple reedsolo at the same time

### ISSUE THREAD

**Issue by Sec42** [tomerfiliba/reedsolomon#26]
I have code that needs to verify two different reedsolo checksums at different times.

one with c_exp=8, the second one with c_exp=6.

My current solution is to copy reedsolo.py to reedsolo6.py and import both reedsolo and reedsolo6 so i can have two instances.

It would be nice if this were supported out of the box :-)

**Comment by lrq3000** [comment]
Are you instanciating two RSCodec objects or are you accessing the internal
functions directly?

If you use the RSCodec object, it should automatically switch the
precomputed tables to match the field you initiated the RSCodec with.

**Comment by Sec42** [comment]
You are right. I was using an old version of reedsolo.py and doing things via reedsolo.init_tables and then reedsolo.rs_correct_msg / reedsolo.rs_encode_msg at the moment. partly because I had known erasures & needed to know how many errors were corrected.

Taking a second look at the documentation it seems that it should work via the object interface. Will try & report back.

Thanks

**Comment by Sec42** [comment]
I managed to do it with the RSCodec class interface. Sorry for the noise.
